// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package sqlc

import (
	"database/sql"
	"time"
)

type Dividend struct {
	ID          int32
	Ticker      string
	DollarValue sql.NullString
	ReceivedOn  time.Time
}
