// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createDividends = `-- name: CreateDividends :exec
INSERT INTO dividends (ticker, dollar_value, received_on) VALUES ($1, $2, $3)
`

type CreateDividendsParams struct {
	Ticker      string
	DollarValue sql.NullString
	ReceivedOn  time.Time
}

func (q *Queries) CreateDividends(ctx context.Context, arg CreateDividendsParams) error {
	_, err := q.db.ExecContext(ctx, createDividends, arg.Ticker, arg.DollarValue, arg.ReceivedOn)
	return err
}
