version: '3.8'
services:
  postgres:
    image: timescale/timescaledb-ha:pg15-latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=m1finance
    volumes:
      - ./tmpdata/pg_data:/data/db
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
      - ./tmpdata/grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning