version: '3'
tasks:
  # Docker Compose
  docker:up:
    cmds:
      - docker compose up -d
    env:
      COMPOSE_PROJECT_NAME: m1-finance-grafana
  docker:down:
    cmds:
      - docker compose down
    env:
      COMPOSE_PROJECT_NAME: m1-finance-grafana

  # Postgres
  pg:migrate:
    cmds:
      - migrate -source $MIGRATIONS_PATH -database $POSTGRES_URL
    env:
      MIGRATIONS_PATH: ./database/migrations
      POSTGRES_URL: postgres://user:pass@localhost:5432/m1finance