version: '3'
tasks:
  # Docker Compose
  docker:up:
    cmds:
      - docker compose up -d
    env:
      COMPOSE_PROJECT_NAME: m1-finance-grafana

  docker:down:
    cmds:
      - docker compose down
    env:
      COMPOSE_PROJECT_NAME: m1-finance-grafana

  # Timescale
  ts:migrate:
    cmds:
      - migrate -database "$POSTGRES_URL" -path "$MIGRATIONS_PATH" up
    env:
      MIGRATIONS_PATH: ./database/migrations
      POSTGRES_URL: postgres://user:pass@localhost:5432/m1finance?sslmode=disable

  ts:migration:generate:
    cmds:
      - migrate create -dir ./database/migrations -ext sql {{.MIGRATION_NAME}}

  # Parse Dividends
  parse-dividends:
    cmds:
      - cd parse-dividends && go run main.go
  parse-dividends:sqlc:generate:
    cmds:
      - cd parse-dividends && sqlc generate