{
 "title": "Dividends",
 "time": { "from": "2023-06-01T00:00:00.000Z", "to": "2023-06-30T00:00:00.000Z" },
 "refresh": "1d",
 "templating": {
  "list": [
   { "name": "bucket_interval", "label": "Bucket Interval", "query": "1d,7d,14d,30d" }
  ]
 },
 "panels": [
  {
   "title": "Dividends Earned Over Time",
   "type": "timeseries",
   "description": "Displays dividends earned as a time series. This includes dividend deductions as part of the day to day sum calculation.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CAST(SUM(dollar_value) AS NUMERIC) as \"Earned Dividends\",\n  time_bucket('$bucket_interval', received_on) as received_on\nFROM\n  dividends\nWHERE\n  received_on >= $__timeFrom() :: timestamptz\n  AND received_on < $__timeTo() :: timestamptz\nGROUP BY\n  time_bucket('$bucket_interval', received_on)\nORDER BY\n  received_on"
    }
   ]
  },
  {
   "title": "Total Dividends Earned",
   "type": "stat",
   "description": "Displays total dividends earned during period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CAST(SUM(dollar_value) AS NUMERIC) as \"Earned Dividends\",\n  time_bucket('$bucket_interval', received_on) as received_on\nFROM\n  dividends\nWHERE\n  received_on >= $__timeFrom() :: timestamptz\n  AND received_on < $__timeTo() :: timestamptz\nGROUP BY\n  time_bucket('$bucket_interval', received_on)\nORDER BY\n  received_on"
    }
   ]
  },
  {
   "title": "Top Earners",
   "type": "bargauge",
   "description": "Displays breakdown of dividends earned by each ticker during the period sorted by dollar value.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ticker as metric,\n  CAST(SUM(dollar_value) AS NUMERIC) as value\nFROM\n  dividends\nWHERE\n  received_on >= $__timeFrom() :: timestamptz\n  AND received_on < $__timeTo() :: timestamptz\nGROUP BY\n  ticker\nORDER BY\n  value DESC\nLIMIT\n  20;"
    }
   ]
  },
  {
   "title": "Recent Dividends",
   "type": "table",
   "description": "Dividends earned recently.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ticker as \"Ticker\",\n  dollar_value as \"Amount\",\n  received_on as \"Received On\"\nFROM\n  dividends\nWHERE\n  received_on >= $__timeFrom() :: timestamptz\n  AND received_on < $__timeTo() :: timestamptz\nORDER BY\n  received_on DESC\nLIMIT\n  100;"
    }
   ]
  }
 ]
}